import { writeFileSync } from "node:fs";
import { allRules } from "../src/rules/index.js";

const L: string[] = [
  "# Detection rules",
  "",
  "<!-- Generated by `npm run docs:rules` from src/rules. Do not edit by hand. -->",
  "",
  "Every finding carries a stable rule ID. Findings are **indicators**, not proof of a vulnerability: each one includes the evidence that triggered it so false positives are easy to investigate.",
  "",
  "| ID | Severity | Category | Name |",
  "|---|---|---|---|",
  ...allRules().map((r) => `| [${r.id}](#${r.id.toLowerCase()}) | ${r.severity} | ${r.category} | ${r.name} |`),
  "",
];
for (const r of allRules()) {
  L.push(
    `## ${r.id}`,
    "",
    `**${r.name}** — default severity **${r.severity}**, category \`${r.category}\`${r.group ? `, config key \`rules.${r.group}\`` : ""}.`,
    "",
    `**What it detects.** ${r.description}`,
    "",
    `**Why it matters.** ${r.why}`,
    "",
    `**How to fix.** ${r.recommendation}`,
    "",
    "Disable or re-level it in `mcp-detector.yml`:",
    "",
    "```yaml",
    "rules:",
    `  ${r.id}: off      # or: low | medium | high | critical`,
    "```",
    "",
  );
}
writeFileSync("docs/rules.md", L.join("\n"), "utf8");
console.log(`Wrote docs/rules.md (${allRules().length} rules)`);
